apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: pvc-pod
      image: ubuntu
      command:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: /data
          name: csi-volume
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  volumes:
    - name: csi-volume
      persistentVolumeClaim:
        claimName: pvc-encrypted-example
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linode-block-storage-encrypted
  namespace: kube-system
parameters:
  linodebs.csi.linode.com/encrypted: "true"
allowVolumeExpansion: true
provisioner: linodebs.csi.linode.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-encrypted-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-encrypted