name: Publish Docker Release
on:
  push:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3.5.0
        with:
          fetch-depth: 0
      - name: Save revision
        run: echo "REV=$(git describe --long --tags --dirty)" >> $GITHUB_ENV
      - name: Build and Publish latest release to Registry
        uses: elgohr/Publish-Docker-Github-Action@43dc228e327224b2eda11c8883232afd5b34943b # pin@v5
        with:
          # TODO(PR): revert the username, we're just being safe for now
          name: okokes/linode-blockstorage-csi-driver
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ github.event.release.tag_name }}"
          dockerfile: "./app/linode/Dockerfile"
          buildargs: REV
          # TODO(PR): use no_push to build on each commit, but only push on release
          no_push: ${{ github.event_name == 'push' }}
