name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20']
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: make lint